import { Asset, FinancialCategory, FinancialType } from './types';

export const INITIAL_FINANCIAL_TYPES: FinancialType[] = [
    { id: 't1', name: 'Ввод', isIncome: true },
    { id: 't2', name: 'Вывод Средств', isIncome: false },
    { id: 't3', name: 'Вывод Прибыли', isIncome: false },
];

export const INITIAL_FINANCIAL_CATEGORIES: FinancialCategory[] = [
    { id: '1', typeId: 't1', name: 'Ввод средств', currency: 'USD' },
    { id: '2', typeId: 't2', name: 'USDT - Fianor Карта', currency: 'USD' },
    { id: '3', typeId: 't2', name: 'USDT - Fianor Счет', currency: 'USD' },
    { id: '4', typeId: 't2', name: 'USDT - Canal Bank', currency: 'USD' },
    { id: '5', typeId: 't2', name: 'USDT - Костыль', currency: 'USD' },
    { id: '6', typeId: 't2', name: 'USDT - Роман', currency: 'USD' },
    { id: '7', typeId: 't2', name: 'USDT - Сергей', currency: 'USD' },
    { id: '8', typeId: 't2', name: 'USDT - Марина', currency: 'USD' },
    { id: '9', typeId: 't2', name: 'USDT - Иван', currency: 'USD' },
    { id: '10', typeId: 't2', name: 'USDT - LIMO BRASIL', currency: 'USD' },
    { id: '11', typeId: 't2', name: 'USDT - Tower Bank', currency: 'USD' },
    { id: '12', typeId: 't2', name: 'USDT - Костя-Кот', currency: 'USD' },
    { id: '13', typeId: 't3', name: 'EUR > Revolut', currency: 'EUR' },
    { id: '14', typeId: 't3', name: 'USDT > Revolut', currency: 'USD' },
    { id: '15', typeId: 't3', name: 'USDT > Canal Bank', currency: 'USD' },
    { id: '16', typeId: 't3', name: 'USDT > Костыль', currency: 'USD' },
    { id: '17', typeId: 't2', name: 'USDT - Revolut', currency: 'USD' },
    { id: '18', typeId: 't3', name: 'USDT > Tower Bank', currency: 'USD' },
];

export const INITIAL_ASSETS: Asset[] = [
    { id: '1', name: '0G', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '2', name: '1000000MOG', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '3', name: '1000BONK', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '4', name: '1000CHEEMS', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '5', name: '1000FLOKI', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '6', name: '1000LUNC', scenario: 6000, steps: [true, true, true, false], isActive: true, isVerified: false, orders: false },
    { id: '7', name: '1000PEPE', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '8', name: '1000SHIB', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '9', name: '1000XEC', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '10', name: '1INCH', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '11', name: '1MBABY DOGE', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '12', name: '2Z', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '13', name: 'A', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '14', name: 'AAVE', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '15', name: 'ACH', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '16', name: 'ADA', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '17', name: 'AERO', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '18', name: 'AEVO', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '19', name: 'AIXBT', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '20', name: 'AKT', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '21', name: 'ALGO', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '22', name: 'ALPINE', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '23', name: 'ALT', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '24', name: 'ANKR', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '25', name: 'APE', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '26', name: 'APT', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '27', name: 'AR', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '28', name: 'ARB', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '29', name: 'ARKM', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '30', name: 'ASTER', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '31', name: 'ASTR', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '32', name: 'ATH', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '33', name: 'ATOM', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '34', name: 'AVAX', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '35', name: 'AVNT', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '36', name: 'AWE', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '37', name: 'AXL', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '38', name: 'AXS', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '39', name: 'B', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '40', name: 'BABY', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '41', name: 'BAND', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '42', name: 'BANK', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '43', name: 'BARD', scenario: 1500, steps: [true, true, true, false], isActive: true, isVerified: true, orders: false },
    { id: '44', name: 'BAS', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '45', name: 'BB', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '46', name: 'BEAMX', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '47', name: 'BERA', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '48', name: 'BICO', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '49', name: 'BIGTIME', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '50', name: 'BIO', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '51', name: 'BLUR', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '52', name: 'BOME', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '53', name: 'BRETT', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '54', name: 'BSV', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '55', name: 'CAKE', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '56', name: 'CC', scenario: 1500, steps: [true, true, false, false], isActive: true, isVerified: false, orders: false },
    { id: '57', name: 'CELO', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '58', name: 'CFX', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '59', name: 'CHZ', scenario: 3000, steps: [true, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '60', name: 'CKB', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '61', name: 'CLOU', scenario: 3000, steps: [true, true, false, false], isActive: true, isVerified: true, orders: false },
    { id: '62', name: 'COAI', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '63', name: 'COMP', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '64', name: 'COTI', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '65', name: 'COW', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '66', name: 'CRV', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '67', name: 'DASH', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '68', name: 'DEEP', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '69', name: 'DEXE', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '70', name: 'DOGE', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '71', name: 'DOT', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '72', name: 'DRIFT', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '73', name: 'DYDX', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '74', name: 'EGLD', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '75', name: 'EIGEN', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '76', name: 'ENA', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '77', name: 'ENJ', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '78', name: 'ENS', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '79', name: 'ERA', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '80', name: 'ETC', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '81', name: 'ETHFI', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '82', name: 'ETHW', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '83', name: 'FARTCOIN', scenario: 6000, steps: [true, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '84', name: 'FET', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '85', name: 'FF', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '86', name: 'FIL', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '87', name: 'FLOW', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '88', name: 'FORM', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '89', name: 'FUN', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '90', name: 'FXS', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '91', name: 'G', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '92', name: 'GALA', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '93', name: 'GAS', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '94', name: 'GIGGLE', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '95', name: 'GLM', scenario: 1500, steps: [true, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '96', name: 'GMT', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '97', name: 'GMX', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '98', name: 'GRASS', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '99', name: 'GRT', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '100', name: 'HBAR', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '101', name: 'HIPPO', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '102', name: 'HOLO', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '103', name: 'HOME', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '104', name: 'HOT', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '105', name: 'HYPE', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '106', name: 'ICP', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '107', name: 'ICX', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '108', name: 'ID', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '109', name: 'ILV', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '110', name: 'IMX', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '111', name: 'INJ', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '112', name: 'IO', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '113', name: 'IOST', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '114', name: 'IOTA', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '115', name: 'IOTX', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '116', name: 'IP', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '117', name: 'JASMY', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '118', name: 'JCT', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '119', name: 'JST', scenario: 1500, steps: [true, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '120', name: 'JTO', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '121', name: 'JUP', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '122', name: 'KAIA', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '123', name: 'KAITO', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '124', name: 'KAS', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '125', name: 'KAVA', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '126', name: 'KMNO', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '127', name: 'KSM', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '128', name: 'LAYER', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '129', name: 'LDO', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '130', name: 'LIGHT', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '131', name: 'LINEA', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '132', name: 'LINK', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '133', name: 'LISTA', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '134', name: 'LPT', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '135', name: 'LRC', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '136', name: 'LTC', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '137', name: 'MANA', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '138', name: 'MASK', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '139', name: 'ME', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '140', name: 'MELANIA', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '141', name: 'MEME', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '142', name: 'MET', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '143', name: 'METIS', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '144', name: 'MEW', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '145', name: 'MINA', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '146', name: 'MIRA', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '147', name: 'MMT', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '148', name: 'MOCA', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '149', name: 'MOODENG', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '150', name: 'MORPHO', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '151', name: 'MOVE', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '152', name: 'MYX', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '153', name: 'NEAR', scenario: 3000, steps: [true, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '154', name: 'NEIRO', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '155', name: 'NEO', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '156', name: 'NIL', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '157', name: 'NMR', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '158', name: 'NOM', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '159', name: 'NOT', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '160', name: 'NXPC', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '161', name: 'OM', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '162', name: 'ONDO', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '163', name: 'ONE', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '164', name: 'ONT', scenario: 6000, steps: [true, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '165', name: 'OP', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '166', name: 'OPEN', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '167', name: 'ORCA', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '168', name: 'ORDER', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '169', name: 'ORDI', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '170', name: 'PENDLE', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '171', name: 'PENGU', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '172', name: 'PLUME', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '173', name: 'PNUT', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '174', name: 'POL', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '175', name: 'POLYX', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '176', name: 'POPCAT', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '177', name: 'PROM', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '178', name: 'PROVE', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '179', name: 'PTB', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '180', name: 'PUMP', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '181', name: 'PUNDIX', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '182', name: 'PYTH', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '183', name: 'QNT', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '184', name: 'QTUM', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '185', name: 'RAYSOL', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '186', name: 'RED', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '187', name: 'RENDER', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '188', name: 'RIVER', scenario: 6000, steps: [true, true, false, false], isActive: true, isVerified: false, orders: false },
    { id: '189', name: 'RLC', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '190', name: 'RONIN', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '191', name: 'ROSE', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '192', name: 'RPL', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '193', name: 'RSR', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '194', name: 'RUNE', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '195', name: 'RVN', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '196', name: 'S', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '197', name: 'SAFE', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '198', name: 'SAHARA', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '199', name: 'SAND', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '200', name: 'SCRT', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '201', name: 'SEI', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '202', name: 'SFP', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '203', name: 'SKL', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '204', name: 'SNX', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '205', name: 'SOL', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '206', name: 'SOMI', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '207', name: 'SOON', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '208', name: 'SPK', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '209', name: 'SQD', scenario: 3000, steps: [true, true, true, false], isActive: true, isVerified: false, orders: false },
    { id: '210', name: 'SSV', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '211', name: 'STABLE', scenario: 1500, steps: [true, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '212', name: 'STBL', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '213', name: 'STG', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '214', name: 'STORJ', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '215', name: 'STRK', scenario: 3000, steps: [true, true, true, false], isActive: true, isVerified: false, orders: false },
    { id: '216', name: 'STX', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '217', name: 'SUI', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '218', name: 'SUPER', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '219', name: 'SUSHI', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '220', name: 'SXT', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '221', name: 'SYRUP', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '222', name: 'T', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '223', name: 'TAO', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '224', name: 'THETA', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '225', name: 'TIA', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '226', name: 'TON', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '227', name: 'TRB', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '228', name: 'TRUMP', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '229', name: 'TRUTH', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '230', name: 'TURBO', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '231', name: 'TWT', scenario: 3000, steps: [true, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '232', name: 'UMA', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '233', name: 'UNI', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '234', name: 'VANA', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '235', name: 'VET', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '236', name: 'VINE', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '237', name: 'VIRTUAL', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '238', name: 'VTHO', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '239', name: 'W', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '240', name: 'WAL', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '241', name: 'WIF', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '242', name: 'WLD', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '243', name: 'WLFI', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '244', name: 'WOO', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '245', name: 'XAN', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '246', name: 'XLM', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '247', name: 'XPL', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '248', name: 'XTZ', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '249', name: 'XVG', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '250', name: 'XVS', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '251', name: 'YFI', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '252', name: 'YGG', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '253', name: 'ZETA', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '254', name: 'ZIL', scenario: 6000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '255', name: 'ZK', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '256', name: 'ZKC', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '257', name: 'ZKJ', scenario: 12000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '258', name: 'ZORA', scenario: 1500, steps: [false, false, false, false], isActive: true, isVerified: true, orders: false },
    { id: '259', name: 'ZRO', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
    { id: '260', name: 'ZRX', scenario: 3000, steps: [false, false, false, false], isActive: true, isVerified: false, orders: false },
];
